"""Types for the native API used by Validity (bittensor-core 0.1.3 ships no stubs)."""

from typing import Self

CRYPTO_ED25519: int
CRYPTO_SR25519: int

class Keypair:
    def __init__(
        self,
        ss58_address: str | None = None,
        public_key: bytes | None = None,
        crypto_type: int = 1,
        ss58_format: int = 42,
    ) -> None: ...
    @classmethod
    def create_from_uri(cls, uri: str, crypto_type: int = 1) -> Self: ...
    @classmethod
    def create_from_mnemonic(cls, mnemonic: str, crypto_type: int = 1, password: str | None = None) -> Self: ...
    @classmethod
    def create_from_seed(cls, seed: bytes, crypto_type: int = 1) -> Self: ...
    @classmethod
    def create_from_private_key(cls, private_key: str, crypto_type: int = 1) -> Self: ...
    @property
    def ss58_address(self) -> str: ...
    @property
    def public_key(self) -> bytes: ...
    @property
    def crypto_type(self) -> int: ...
    @property
    def ss58_format(self) -> int: ...
    def sign(self, message: bytes) -> bytes: ...
    def verify(self, message: bytes, signature: bytes) -> bool: ...

def ss58_decode(ss58_address: str) -> bytes: ...
def ss58_encode(public_key: bytes, ss58_format: int = 42) -> str: ...
def serialized_keypair_to_keyfile_data(keypair: Keypair) -> bytes: ...
def deserialize_keypair_from_keyfile_data(data: bytes) -> Keypair: ...
